"""mantis init — interactive scaffolder for .mantis.yaml + .env.example.

Asks four questions: provider, fast model, mid model, deep model. Writes
the config and an env-example file. Refuses to overwrite without --force.
"""
from __future__ import annotations

import sys
from pathlib import Path


_PRESETS: dict[str, dict[str, str | None]] = {
    "google": {
        "fast": "gemini/gemini-2.5-flash-lite",
        "mid": "gemini/gemini-2.5-flash",
        "deep": "gemini/gemini-2.5-pro",
        "env": "GEMINI_API_KEY",
        "api_base": None,
    },
    "anthropic": {
        "fast": "claude-haiku-4-5",
        "mid": "claude-sonnet-4-6",
        "deep": "claude-opus-4-7",
        "env": "ANTHROPIC_API_KEY",
        "api_base": None,
    },
    "openai": {
        "fast": "gpt-4o-mini",
        "mid": "gpt-4o",
        "deep": "gpt-4o",
        "env": "OPENAI_API_KEY",
        "api_base": None,
    },
    "openrouter": {
        "fast": "openrouter/anthropic/claude-haiku-4-5",
        "mid": "openrouter/anthropic/claude-sonnet-4-6",
        "deep": "openrouter/anthropic/claude-opus-4-7",
        "env": "OPENROUTER_API_KEY",
        "api_base": None,
    },
    "ollama": {
        "fast": "ollama/qwen2.5-coder:7b",
        "mid": "ollama/qwen2.5-coder:14b",
        "deep": "ollama/qwen2.5-coder:32b",
        "env": None,
        "api_base": "http://localhost:11434",
    },
}


def _ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        v = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        v = ""
    return v or (default or "")


def _ask_choice(prompt: str, choices: list[str], default: str) -> str:
    print(f"{prompt}")
    for i, c in enumerate(choices, 1):
        marker = " (default)" if c == default else ""
        print(f"  {i}) {c}{marker}")
    raw = _ask("choose", default)
    if raw.isdigit() and 1 <= int(raw) <= len(choices):
        return choices[int(raw) - 1]
    if raw in choices:
        return raw
    return default


def cmd_init(args) -> int:
    target = Path(getattr(args, "path", ".") or ".").resolve()
    force = bool(getattr(args, "force", False))
    if not target.is_dir():
        print(f"target not found: {target}", file=sys.stderr)
        return 2

    cfg_path = target / ".mantis.yaml"
    env_path = target / ".env.example"

    if cfg_path.exists() and not force:
        print(f"{cfg_path} already exists. Re-run with --force to overwrite.",
              file=sys.stderr)
        return 2

    print(f"scaffolding mantis config in {target}")
    print()
    provider = _ask_choice("LLM provider:", list(_PRESETS.keys()), "google")
    preset = _PRESETS[provider]

    fast = _ask("fast tier model", str(preset["fast"]))
    mid = _ask("mid tier model", str(preset["mid"]))
    deep = _ask("deep tier model", str(preset["deep"]))
    sast = _ask_choice("SAST binary:", ["auto", "opengrep", "semgrep"], "auto")

    lines = [
        "# mantis config — generated by `mantis init`.",
        f"provider: {provider}",
        "models:",
        f"  fast: {fast}",
        f"  mid:  {mid}",
        f"  deep: {deep}",
        "budget:",
        "  max_findings:   200",
        "  max_deep_calls: 50",
        f"sast_bin: {sast}",
    ]
    api_base = preset.get("api_base")
    if api_base:
        lines.append(f"api_base: {api_base}")
    cfg_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {cfg_path}")

    env_var = preset.get("env")
    if env_var:
        if env_path.exists() and not force:
            print(f"  (skipped {env_path} — already exists; pass --force to overwrite)")
        else:
            env_path.write_text(f"{env_var}=your-key-here\n", encoding="utf-8")
            print(f"wrote {env_path}  (set {env_var} in your shell before running `mantis audit`)")

    # Make sure .mantis/ is gitignored so future history dirs don't get committed.
    gi = target / ".gitignore"
    needs = ".mantis/\n"
    try:
        existing = gi.read_text(encoding="utf-8") if gi.is_file() else ""
        if ".mantis/" not in existing and ".mantis" not in existing.split():
            with gi.open("a", encoding="utf-8") as f:
                if existing and not existing.endswith("\n"):
                    f.write("\n")
                f.write(needs)
            print(f"appended .mantis/ to {gi}")
    except OSError:
        pass

    print()
    print("next: `mantis doctor` to verify, then `mantis audit`.")
    return 0
